### ISSUE TITLE
Content Negotiation

### ISSUE THREAD

**Issue by bsesic** [judaicalink/judaicalink-labs#299]
Content Negotiation is not working.
https://github.com/judaicalink/judaicalink-labs/wiki/Content-Negotiation

**Comment by bsesic** [comment]
Read the dokumenation here: https://github.com/judaicalink/judaicalink-labs/wiki/Content-Negotiation.

**Comment by bsesic** [comment]
# TODO

- [ ] Fix url resolving.
- [ ] Fix n-triples output.
- [ ] FIx turtle output.
- [ ] Add links with icons to the template.

**Comment by bsesic** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation

Icons: 
https://cygri.github.io/rdf-logos/
https://www.w3.org/RDF/icons/

**Comment by bsesic** [comment]
PDF generation: https://docs.djangoproject.com/en/5.1/howto/outputting-pdf/

**Comment by bsesic** [comment]
https://www.w3.org/2007/10/sw-logos.html
